= Content Focus

// tag::summary[]
Browser extension pruning websites to focus on the content.
Don't block unnecessary items, delete everything but the focus.
// end::summary[]

== Concept

Extension applies to all websites.
Extension allows configuration of focus elements (per website).
Extension hides all elements but the focus elements when in focus mode.
Extension allows to toggle focus mode.
Extension can prevent event-based impediments on focus elements (e.g. context menu blockers).
Extension can auto-click elements (e.g. decline cookies, close login requests).

== Realization

When applicable website loads, the content script is executed.
The content script uses DOM observers to wait for the focus elements to load.
Once the focus elements are present, focus mode is engaged by hiding all unrelated HTML nodes.
Unrelated HTML elements are all elements that do not lie on the paths from body to focus elements.

Additionally, event listeners can be overriden for elements (e.g. oncontextmenu).
Elements can also be automatically clicked as soon as they pop up.

The focus mode can be toggled via the extension popup.
The extension popup registers a click on the toggle button.
The extension popup then sends a event to the content script.
The content-script reloads all unrelated HTML elements.

In the options menu focus elements can be configured per website.
The configuration is done with CSS selectors.

=== Assets

Sources on link:https://github.com/devnsi/content-focus[github.com]. +
Styles by link:https://simplecss.org[simplecss.org]. +
Icons by link:https://icons8.com[icons8.com].
